# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.centralTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.centralTabs.setObjectName("centralTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.centralTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.centralTabs.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.centralTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        self.menuDiagram = QtWidgets.QMenu(self.menubar)
        self.menuDiagram.setObjectName("menuDiagram")
        self.menuRule = QtWidgets.QMenu(self.menubar)
        self.menuRule.setObjectName("menuRule")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewDiagram = QtWidgets.QAction(MainWindow)
        self.actionNewDiagram.setObjectName("actionNewDiagram")
        self.actionNewRule = QtWidgets.QAction(MainWindow)
        self.actionNewRule.setObjectName("actionNewRule")
        self.menuDiagram.addAction(self.actionNewDiagram)
        self.menuRule.addAction(self.actionNewRule)
        self.menubar.addAction(self.menuDiagram.menuAction())
        self.menubar.addAction(self.menuRule.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.centralTabs.setTabText(self.centralTabs.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.centralTabs.setTabText(self.centralTabs.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuDiagram.setTitle(_translate("MainWindow", "&Diagram"))
        self.menuRule.setTitle(_translate("MainWindow", "&Rule"))
        self.actionNewDiagram.setText(_translate("MainWindow", "&New"))
        self.actionNewDiagram.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionNewRule.setText(_translate("MainWindow", "&New"))
